Day 3/milena
kristina-kolosek/react-5-days pull request #11
Opened 2018-06-01 10:16 UTC by milena-kolosek

2018-06-01 13:54 UTC, kristina-kolosek commented
I get an error "Cannot read property 'status' of undefined" when trying to save api key (src/reducers/AuthenticationReducer/actions.js:18)

2018-06-01 14:13 UTC, kristina-kolosek requested changes
Besides these comments I left, idea is to also keep the selected branch if route is refreshed In your case, it'd be a bit more complex, so try doing it for desktop devices only

2018-06-01 14:13 UTC, kristina-kolosek commented on src/CircleCiRoute/index.js
> +    sessionStorage.getItem('circleCiToken') ? <Component {...props} /> : <Redirect to='/auth' />
Great job on this, this is the most proper way to handle authorization

2018-06-01 14:13 UTC, kristina-kolosek commented on src/components/CircleCiBuildDetails/index.js
> +          Status: <label className={'status-' + status}>{status.charAt(0).toUpperCase() + status.slice(1)}</label>
Either move this out as capitalize utility function, or use loads utility :). + it'd be the most proper capitalization if the rest was lower-cased

2018-06-01 14:13 UTC, kristina-kolosek commented on src/components/CircleCiBuilds/index.js
> +                key={"commit-" + i}
the most proper key for this list would be what uniquely identifies the build:

vcs type + project + branch + build number

2018-06-01 14:13 UTC, kristina-kolosek commented on src/components/Commit/index.js
> +             <label className={'status-' + status}>{status.charAt(0).toUpperCase() + status.slice(1)}</label>
Same comment as above, regarding capitalization

2018-06-01 14:13 UTC, kristina-kolosek commented on src/pages/AuthenticatePage/index.js
> +        this.props.history.push("/");
better use setting of state + redirect component, a more proper way than programmatically pushing

2018-06-25 12:53 UTC, milena-kolosek commented
I'm not sure what you meant by 'to keep the selected branch if route is refreshed In your case'.
I'm saving the selected branch in the store state as 'commitDetails'.

2018-06-27 18:52 UTC, kristina-kolosek commented on src/components/CircleCiBuilds/index.js
> +                key={i + '-' + build.id + '-' + build.branchName + '-' + build.projectName + '-'}
Isn't it easier to use `${i}-${build.id}-${build.branchName}-${build.projectName}-` instead? (I'm not quite a fan of string concatenation :D)

2018-06-27 18:58 UTC, kristina-kolosek commented
Reducer state is wiped off on page refresh, so you'd need a parameter in route to persist it and make more SEO friendly

2018-07-03 07:42 UTC, closed without merging